import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {firebaseConfig, database} from '../firebaseConfig'
import { collection, addDoc } from 'firebase/firestore';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Button } from '@mui/material';

export default function Home() {


  return (

    <div className={styles.container}>
      <Head>
        <title>Series Purge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-4xl font-bold">Series Purge</h1>
        <p>Sort out Tvseries of your choice by choosing from over a million different Tvseries </p>
        <Link href='/components/authentication'>
          <Button variant="contained">Login / Signup</Button>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
